repos:
  - repo: https://github.com/ddanier/sub-pre-commit.git
    rev: v4.0.1  # MUST match your pre-commit version
    hooks:
      - id: sub-pre-commit
        args: ["-p", "server"]
        files: "^server/.*"
        stages: ["pre-commit"]
