repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.9.6
  hooks:
    - id: ruff
      args: [--fix]
- repo: https://github.com/python-poetry/poetry
  rev: 2.0.1 
  hooks:
    - id: poetry-check
    - id: poetry-lock
    - id: poetry-install
