FROM python:3.13-slim
WORKDIR /app
RUN pip install poetry
COPY pyproject.toml poetry.lock ./
RUN poetry install --no-cache --without dev
COPY . .
CMD poetry run celery -A worker.cleanup_refresh_tokens worker -B -c 1
